dataset:
  name: xyz
  dataset_path: ../dataset
  train_ratio: 0.9
  batchsize: 4
  random_seed: 1112
trainer:
  provider: deepmd
  method: default
  parameters:
    config: ./dpa4c.json
    train_epochs: 10
    print_epochs: 1
    train_batches: null
    random_seed: 1112
