potential:
  provider: emt
executor:
  provider: ase
  method: cmin
  parameters:
    setup:
      optimizer:
        name: bfgs
        parameters:
          isotropic: true
          pressure: 0.0
    stop:
      fmax: 0.02
      steps: 100
