potential:
  provider: emt
executor:
  provider: ase
  method: md
  parameters:
    random_seed: 7
    setup:
      ensemble: nvt
      timestep: 1.0
      velocities:
        initialize: if_missing
        seed: 7
      regulator:
        name: berendsen
        targets:
          temperature: 300
        parameters:
          Tdamp: 100.0
    output:
      trajectory:
        period: 10
    stop:
      steps: 100
