potential:
  provider: emt
executor:
  provider: ase
  method: neb
  parameters:
    setup:
      nimages: 5
      interpolation:
        mic: false
      climb: false
      constraint: "1:8"
    output:
      trajectory:
        period: 5
    stop:
      fmax: 0.08
      steps: 100
