potential:
  provider: nnp
  parameters:
    model_file: ./nnp_train/nn_weights.npz
    type_map: ["Cu", "Au"]

executor:
  provider: ase
  method: md
  parameters:
    setup:
      timestep: 1.0
      ensemble: nvt
      regulator:
        name: langevin
        targets:
          temperature: 300.0
    output:
      trajectory:
        period: 100
    stop:
      steps: 10000
scheduler:
  provider: direct
  parameters: {}
  transport:
    provider: local
    parameters: {}
dispatch:
  batch_size: 1
