potential:
  provider: emt
executor:
  provider: ase
  method: min
  parameters:
    random_seed: 7
    output:
      trajectory:
        period: 1
    stop:
      fmax: 0.05
      steps: 100
dispatch:
  batch_size: 3
