{% set name = "gdpx" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/g/gdpx/gdpx-0.0.10.tar.gz
  sha256: ffd485f15bd65553f42ae365c5e70b428d38ed75dad633a7429d270a26de3051

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gdp = gdpx.main:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - ase >=3.23
    - h5py >=3.7.0
    - joblib >=1.1.0
    - networkx >=2.6.3
    - omegaconf >=2.3.0
    - pyyaml >=6.0
    - tinydb >=4.7.0

test:
  imports:
    - gdpx
  requires:
    - pip
  commands:
    - pip check
    - gdp -h  # [not win]

about:
  home: https://github.com/hsulab/GDPy
  summary: "Automate computational chemistry/materials sciance and machine learning interatomic potential training workflow."
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  dev_url: https://github.com/hsulab/GDPy

extra:
  recipe-maintainers:
    - hsulab
