{% set name = "gdpx" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b909a8d674da1aa59af34dcabf6ee6dcb4405f27e6efc98ea9eed3c20fb8b03

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - gdp = gdpx.main:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61
  run:
    - python >=3.10
    - ase >=3.24,<3.27
    - h5py >=3.7.0
    - joblib >=1.1.0
    - networkx >=2.6.3
    - omegaconf >=2.3.0
    - pyyaml >=6.0
    - tinydb >=4.7.0

test:
  imports:
    - gdpx
  requires:
    - pip
  commands:
    - pip check
    - gdp -h  # [not win]

about:
  home: https://github.com/hsulab/GDPy
  summary: "Automate computational chemistry/materials sciance and machine learning interatomic potential training workflow."
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  dev_url: https://github.com/hsulab/GDPy

extra:
  recipe-maintainers:
    - hsulab
